<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<FrontLook>8.26.*</FrontLook>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Report.rdlc" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Report.rdlc">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<!--<ProjectReference Include="..\..\FrontLookCore\FrontLookCoreDbAccessLibrary\FrontLookCoreDbAccessLibrary.Desktop.Rdlc\FrontLookCoreDbAccessLibrary.Desktop.Rdlc.csproj" />-->
		<ProjectReference Include="..\Microsoft.ReportViewer.WinForms\Microsoft.ReportViewer.WinForms.csproj" />
	</ItemGroup>

	<!--

	<ItemGroup Condition="'$(Configuration)'!='Debug'">

		<PackageReference Include="FrontLookCoreLibraryAssembly" Version="$(FrontLook)"><ExcludeAssets>contentFiles</ExcludeAssets></PackageReference>
		<PackageReference Include="FrontLookCoreDbAccessLibrary" Version="$(FrontLook)" />
		<PackageReference Include="FrontLookCoreDbAccessLibrary.Desktop" Version="$(FrontLook)" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)'=='Debug'">
		<ProjectReference Include="..\..\FrontLookCore\FrontLookCoreDbAccessLibrary\FrontLookCoreDbAccessLibrary\FrontLookCoreDbAccessLibrary.csproj" />
		<ProjectReference Include="..\..\FrontLookCore\FrontLookCoreLibraryAssembly\FrontLookCoreLibraryAssembly.csproj" />
	</ItemGroup>
-->

	<ItemGroup>
		<ProjectReference Include="..\..\FrontLookCore\FrontLookCoreLibraryAssembly\FrontLookCoreLibraryAssembly.csproj" />
		<ProjectReference Include="..\..\FrontLookCore\FrontLookCoreDbAccessLibrary\FrontLookCoreDbAccessLibrary.Desktop.Rdlc\FrontLookCoreDbAccessLibrary.Desktop.Rdlc.csproj" />
	</ItemGroup>
	<!--
	<ItemGroup>
		<PackageReference Include="FrontLookCoreDbAccessLibrary.Desktop.Rdlc" Version="$(FrontLook)">
			<ExcludeAssets>contentFiles</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="FrontLookCoreLibraryAssembly" Version="$(FrontLook)">
			<ExcludeAssets>contentFiles</ExcludeAssets>
		</PackageReference>
	</ItemGroup>
	-->
</Project>
